{% set name = "predted" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/syseitz/predTED/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1bb0492a7d8d9acd8f1b6015b36017cea5ed0ccc1a8e76a5ee7ca9f55d020e72

build:
  number: 0
  skip: true  # [py<39 or win]
  run_exports:
    - {{ pin_subpackage("predted", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - setuptools >=64
    - numpy
    - lightgbm
    - llvm-openmp  # [osx]
  run:
    - python >=3.9
    - numpy
    - lightgbm
    - llvm-openmp  # [osx]

test:
  imports:
    - predted
    - predted.features
  commands:
    - predted --version

about:
  home: https://github.com/syseitz/predTED
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast approximate Tree Edit Distance prediction for RNA secondary structures
  description: |
    predTED uses structural features and a LightGBM model to approximate
    pairwise Tree Edit Distances between RNA secondary structures without
    running the expensive exact algorithm. Includes a Python library and
    a standalone CLI binary with OpenMP parallelisation.
  dev_url: https://github.com/syseitz/predTED

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  recipe-maintainers:
    - syseitz
